### ISSUE TITLE
Parameters File Error

### ISSUE THREAD

**Issue by njfdCRH1A** [E233-3639/BVE_E233-3000_Data#1]
At [Paramater.txt](https://github.com/E233-3639/BVE_E233-3000_Data/blob/main/E233-3000/OriginalData/Parameter/Parameter.txt) Line 10:
**AtsCancelNotch = 0** is wrong and cannot be loaded correctly.
Correction (Maybe):
**AtsCancelNotch = 0** → **AtsCancelNotch = 1**

**Comment by E233-3639** [comment]
Thank you for reporting bug. I will be going to fix this issue.

**Comment by E233-3639** [comment]
I have just fixed this issue. Thank you so much!
